[package]
name = "rui"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
rui-macros = { version = "0.1.0", path = "rui-macros" }
wgpu = "26.0.1"
winit = "0.30.12"
